name: build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        target: [esp32, esp32s3, esp32p4]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (${{ matrix.target }})
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v6.0
          target: ${{ matrix.target }}
          command: "idf.py fullclean && idf.py build"
